### ISSUE TITLE
setup 2 chains for development

### ISSUE THREAD

**Issue by taitruong** [arkprotocol/templates#3]
objectives:
- development on minimal 2 chains: Juno and Stargaze
- optional 3rd chain: Terra

Todo:
- evaluate ts-relayer for faster development
- if ts-relayer is feasible:
  - write shell scripts for each chain: start.sh and stop.sh
  - provide test examples for contract interaction (store, instantiate, execute and query on contract for chain A or B)
- if not feasible check whether local chain or test nets for chain A or B would be fine
- update README with how-to

**Comment by Art3miX** [comment]
We have a testing with 2 chains, should be closed?

**Comment by tot-truong** [comment]
> We have a testing with 2 chains, should be closed?

Yes, I think with all the relayer and IBC stuff you've been doing this is outdated
